- id: dir-checker
  name: Directory Structure Validator
  description: Validate directory structure and mandatory files with configurable rules
  entry: python -m dir_checker
  language: python
  always_run: true
  pass_filenames: false
  minimum_pre_commit_version: '0.15.0'
