name: Release Please
on:
  workflow_dispatch:
  # Remove automatic push trigger - only manual releases
  # push:
  #   branches:
  #     - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          skip-labeling: true
